package:
  name: perl-grass
  version: '2.1.0'

build:
  number: 4
  skip: True # [osx]

source:
  fn: v2.1.0.tar.gz
  url: https://github.com/cancerit/grass/archive/v2.1.0.tar.gz
  md5: 3c3ed0f36a2f35b8aa4eb3428f34df26

requirements:
  build:
    - perl-threaded
    - perl-app-cpanminus
    - perl-file-sharedir-install
    - perl-module-build
    - perl-bio-db-sam
    - perl-bioperl
    - perl-gd
    - perl-ipc-system-simple
    - perl-sanger-cgp-vcf
    - perl-encode-locale
    - perl-lwp-simple
    - perl-xml-parser
    - perl-bio-db-hts
    - perl-sanger-cgp-vagrent
  run:
    - perl-threaded
    - perl-ipc-system-simple
    - perl-bioperl
    - perl-bio-db-sam
    - perl-bio-samtools
    - perl-gd
    - perl-sanger-cgp-vcf
    - perl-bio-db-hts
    - perl-sanger-cgp-vagrent

test:
  commands:
    - grass.pl --help

about:
  home: https://github.com/cancerit/grass
  license: GPLv3
  summary: Gene Rearrangement AnalySiS
